"""Legacy baseline: the four pre-Alembic ProofMed tables (no data).

Revision ID: 0000_legacy_baseline
Revises: None
Create Date: 2026-09-03

Hand-authored (NOT autogenerated). Reproduces exactly the schema that
``Base.metadata.create_all()`` produced for the legacy runtime tables before
Alembic became the schema authority (WP-INFRA-1):

* goa_ziffern        - GOAE catalog projection (seeded from app/goa_catalog.py)
* encrypted_backups  - zero-knowledge E2EE cloud backups
* medical_claims     - server-side audit claims (EncryptedString columns are
                       stored as plain TEXT; the encryption is an ORM-level
                       TypeDecorator and is deliberately NOT referenced here)
* claim_line_items   - claim positions (FK -> medical_claims ON DELETE CASCADE,
                       FK -> goa_ziffern)

``medical_claims.status`` keeps its historical representation: a native
PostgreSQL enum type ``claim_status`` (labels PENDING, PROCESSED_FLAGGED,
PROCESSED_CLEAN) and VARCHAR(17) on SQLite.

The eight ``goa_ziffern`` columns that the old startup code added via ad-hoc
``ALTER TABLE ... ADD COLUMN ... DEFAULT ...`` are part of this baseline
WITHOUT server defaults (matching the ORM model and a fresh create_all()).
Databases that were upgraded by that ALTER loop carry server defaults on
those columns; they are stamped, never recreated, so this difference is
tolerated and documented (see app/schema_guard.py, stamp-legacy preflight).

Existing databases are NOT re-created: they are brought under Alembic with
``python -m app.schema_guard stamp-legacy`` (fail-closed preflight) followed
by ``alembic upgrade head``.

Downgrade drops the four tables (and the claim_status type on PostgreSQL) and
REFUSES while legacy rows exist unless PROOFMED_ALLOW_LEGACY_DROP=YES is set.
"""
from __future__ import annotations

import os
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0000_legacy_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CLAIM_STATUS_LABELS: tuple[str, ...] = ("PENDING", "PROCESSED_FLAGGED", "PROCESSED_CLEAN")
LEGACY_DROP_OPT_IN_VAR = "PROOFMED_ALLOW_LEGACY_DROP"


def _claim_status_enum() -> sa.Enum:
    # Native type on PostgreSQL (created together with medical_claims),
    # VARCHAR(17) without CHECK on SQLite - identical to the ORM model.
    return sa.Enum(*CLAIM_STATUS_LABELS, name="claim_status")


def upgrade() -> None:
    op.create_table(
        "goa_ziffern",
        sa.Column("ziffer", sa.String(16), nullable=False),
        sa.Column("title_official", sa.String(512), nullable=False),
        sa.Column("title_patient", sa.String(512), nullable=False),
        sa.Column("rule_time_minutes", sa.Integer(), nullable=False),
        sa.Column("exclusion_ziffern", sa.JSON(), nullable=False),
        # --- formerly added by the ad-hoc ALTER loop in app/database.py ---
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("threshold_multiplier", sa.Float(), nullable=False),
        sa.Column("max_multiplier", sa.Float(), nullable=False),
        sa.Column("fee_simple", sa.Float(), nullable=False),
        sa.Column("fee_threshold", sa.Float(), nullable=False),
        sa.Column("fee_max", sa.Float(), nullable=False),
        sa.Column("max_per_session", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("ziffer"),
    )

    op.create_table(
        "encrypted_backups",
        sa.Column("user_id_hash", sa.String(128), nullable=False),
        sa.Column("ciphertext_base64", sa.Text(), nullable=False),
        sa.Column("iv_base64", sa.String(128), nullable=False),
        sa.Column("salt_base64", sa.String(128), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id_hash"),
    )
    # Historical (redundant with the PK, kept for fidelity with create_all()).
    op.create_index("ix_encrypted_backups_user_id_hash", "encrypted_backups", ["user_id_hash"])

    op.create_table(
        "medical_claims",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("patient_id", sa.Text(), nullable=False),  # EncryptedString -> TEXT
        sa.Column("praxis_name", sa.Text(), nullable=False),  # EncryptedString -> TEXT
        sa.Column("geofence_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.Column("geofence_departure", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_billed_amount", sa.Float(), nullable=False),
        sa.Column("status", _claim_status_enum(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "claim_line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.String(36), nullable=False),
        sa.Column("ziffer", sa.String(16), nullable=False),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        # Unnamed, exactly like the ORM model (PostgreSQL auto-names them).
        sa.ForeignKeyConstraint(["claim_id"], ["medical_claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ziffer"], ["goa_ziffern.ziffer"]),
    )
    op.create_index("ix_claim_line_items_claim_id", "claim_line_items", ["claim_id"])


def downgrade() -> None:
    bind = op.get_bind()
    if os.environ.get(LEGACY_DROP_OPT_IN_VAR) != "YES":
        counts = {
            table: bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar_one()
            for table in ("encrypted_backups", "medical_claims", "claim_line_items")
        }
        populated = {table: n for table, n in counts.items() if n}
        if populated:
            raise RuntimeError(
                "Downgrade refused: legacy tables contain data "
                f"{populated}. Dropping them would destroy ProofMed user data. "
                f"Set {LEGACY_DROP_OPT_IN_VAR}=YES only for throwaway databases."
            )
    op.drop_table("claim_line_items")
    op.drop_table("medical_claims")
    op.drop_table("encrypted_backups")
    op.drop_table("goa_ziffern")
    if bind.dialect.name == "postgresql":
        _claim_status_enum().drop(bind, checkfirst=True)
