"""WP-01: Reference Core V1.1.2 schema skeleton (17 tables, no data).

Revision ID: 0001_reference_core
Revises: None
Create Date: 2026-09-03

Hand-authored (NOT autogenerated). Creates exactly the 17 canonical Reference
Core tables in FK dependency order, with every FK/UNIQUE/CHECK/INDEX named
explicitly and declared inline (SQLite has no ALTER ... ADD CONSTRAINT).

Contains no legacy table CREATE/ALTER/DROP, no GOAE rows, no source rows,
no rule rows. All foreign keys are ON DELETE RESTRICT.

Downgrade drops the 17 tables in reverse order and refuses to run while any
FINALIZED audit evidence manifest exists (INV-022).
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_reference_core"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Portable building blocks (mirrors app/models/reference_core.py)
# ---------------------------------------------------------------------------

def _json() -> sa.types.TypeEngine:
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


HASH = sa.String(128)
USER = sa.String(128)
DECIMAL = sa.Numeric(18, 7)


def _ck_enum(table: str, column: str, values: Sequence[str]) -> sa.CheckConstraint:
    quoted = ", ".join(f"'{value}'" for value in values)
    return sa.CheckConstraint(f"{column} IN ({quoted})", name=f"ck_{table}_{column}")


def _fk(table: str, column: str, target: str) -> sa.ForeignKeyConstraint:
    return sa.ForeignKeyConstraint(
        [column], [target], name=f"fk_{table}_{column}", ondelete="RESTRICT"
    )


SOURCE_CLASSES = (
    "SOURCE_A_LEGAL",
    "SOURCE_B_OFFICIAL_GUIDANCE",
    "SOURCE_C_JURISPRUDENCE",
    "SOURCE_D_INTERPRETIVE",
    "SOURCE_E_PROOFMED",
)
HASH_ALGORITHMS = ("SHA256", "SHA512")
VERIFICATION_STATUSES = (
    "UNVERIFIED",
    "SOURCE_VERIFIED",
    "PROFESSIONALLY_REVIEWED",
    "LEGALLY_REVIEWED",
)
VERIFICATION_STATUSES_3 = ("UNVERIFIED", "SOURCE_VERIFIED", "PROFESSIONALLY_REVIEWED")
VERIFICATION_STATUSES_2 = ("UNVERIFIED", "SOURCE_VERIFIED")


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:
    # 1. source_records ------------------------------------------------------
    op.create_table(
        "source_records",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_class", sa.String(32), nullable=False),
        sa.Column("issuer", sa.String(255), nullable=False),
        sa.Column("document_title", sa.String(512), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source_url", sa.String(2048), nullable=True),
        sa.Column("source_locator", sa.String(512), nullable=True),
        sa.Column("document_hash", HASH, nullable=True),
        sa.Column("document_hash_algorithm", sa.String(16), nullable=True),
        sa.Column("document_hash_scope", sa.String(32), nullable=True),
        sa.Column("canonicalization_method", sa.String(255), nullable=True),
        sa.Column("excerpt_hash", HASH, nullable=True),
        sa.Column("excerpt_hash_scope", sa.String(32), nullable=True),
        sa.Column("excerpt_text", sa.String(2000), nullable=True),
        sa.Column(
            "archive_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'NOT_ARCHIVED'"),
        ),
        sa.Column("archive_url", sa.String(2048), nullable=True),
        sa.Column("archive_hash", HASH, nullable=True),
        sa.Column("archive_hash_scope", sa.String(32), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verification_method", sa.String(64), nullable=True),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("source_id"),
        sa.UniqueConstraint("source_id", "source_class", name="uq_source_records_id_class"),
        _ck_enum("source_records", "source_class", SOURCE_CLASSES),
        _ck_enum("source_records", "document_hash_algorithm", HASH_ALGORITHMS),
        _ck_enum("source_records", "document_hash_scope", ("FULL_DOCUMENT", "ARCHIVED_ARTIFACT")),
        _ck_enum("source_records", "excerpt_hash_scope", ("EXACT_SOURCE_EXCERPT",)),
        _ck_enum(
            "source_records", "archive_status", ("NOT_ARCHIVED", "ARCHIVED", "ARCHIVED_EXTERNALLY")
        ),
        _ck_enum("source_records", "archive_hash_scope", ("ARCHIVE_ARTIFACT",)),
        _ck_enum("source_records", "verification_status", VERIFICATION_STATUSES),
        _ck_enum(
            "source_records",
            "verification_method",
            ("PRIMARY_SOURCE_MATCH", "MANUAL_PROFESSIONAL_REVIEW"),
        ),
        sa.CheckConstraint(
            "(document_hash IS NULL AND document_hash_algorithm IS NULL "
            "AND document_hash_scope IS NULL) "
            "OR (document_hash IS NOT NULL AND document_hash_algorithm IS NOT NULL "
            "AND document_hash_scope IS NOT NULL)",
            name="ck_sr_document_hash_scope",
        ),
        sa.CheckConstraint(
            "(excerpt_hash IS NULL AND excerpt_hash_scope IS NULL) "
            "OR (excerpt_hash IS NOT NULL AND excerpt_hash_scope IS NOT NULL)",
            name="ck_sr_excerpt_hash_scope",
        ),
        sa.CheckConstraint(
            "(archive_hash IS NULL AND archive_hash_scope IS NULL) "
            "OR (archive_hash IS NOT NULL AND archive_hash_scope IS NOT NULL)",
            name="ck_sr_archive_hash_scope",
        ),
    )

    # 2. patient_message_policies ---------------------------------------------
    op.create_table(
        "patient_message_policies",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("finding_type", sa.String(32), nullable=False),
        sa.Column("evidence_level", sa.String(32), nullable=False),
        sa.Column("safe_message_template", sa.Text(), nullable=False),
        sa.Column(
            "should_reference_source", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("source_reference_format", sa.String(512), nullable=True),
        sa.Column("recommended_tone", sa.String(16), nullable=False),
        sa.Column("avoid_language", _json(), nullable=True),
        sa.PrimaryKeyConstraint("policy_id"),
        _ck_enum(
            "patient_message_policies",
            "finding_type",
            (
                "NO_FINDING",
                "REVIEW_NOTE",
                "JUSTIFICATION_REQUIRED",
                "OFFICIAL_GUIDANCE_NOTE",
                "SUPPORTED_CONFLICT",
                "NOT_CONCLUSIVELY_ASSESSABLE",
            ),
        ),
        _ck_enum(
            "patient_message_policies",
            "evidence_level",
            ("STATUTORY_FACT", "OFFICIAL_GUIDANCE", "PROFESSIONAL_REVIEW", "UNRESOLVED"),
        ),
        _ck_enum(
            "patient_message_policies",
            "recommended_tone",
            ("INFORMATIONAL", "ADVISORY", "NEUTRAL"),
        ),
    )

    # 3. verification_records -------------------------------------------------
    op.create_table(
        "verification_records",
        sa.Column("verification_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("verification_level", sa.String(32), nullable=False),
        sa.Column("verification_date", sa.Date(), nullable=False),
        sa.Column("verified_by", USER, nullable=False),
        sa.Column("verification_method", sa.String(512), nullable=True),
        sa.Column("findings", sa.Text(), nullable=True),
        sa.Column("confidence_level", sa.String(32), nullable=True),
        sa.PrimaryKeyConstraint("verification_id"),
        _ck_enum(
            "verification_records",
            "entity_type",
            (
                "SOURCE_RECORD",
                "REFERENCE_ASSERTION",
                "FACTOR_RULE",
                "FEE_CALCULATION_RULE",
                "BILLING_RULE",
                "ANALOG_REFERENCE",
            ),
        ),
        _ck_enum("verification_records", "verification_level", VERIFICATION_STATUSES),
        _ck_enum(
            "verification_records",
            "confidence_level",
            ("HIGH", "MEDIUM", "LOW", "CONFLICTING_EVIDENCE"),
        ),
    )
    op.create_index(
        "ix_verification_records_entity",
        "verification_records",
        ["entity_type", "entity_id"],
    )

    # 4. fee_schedule_editions ------------------------------------------------
    op.create_table(
        "fee_schedule_editions",
        sa.Column("fee_schedule_edition_id", sa.Uuid(), nullable=False),
        sa.Column("fee_schedule_name", sa.String(255), nullable=False),
        sa.Column("jurisdiction", sa.String(64), nullable=False),
        sa.Column("legal_identifier", sa.String(255), nullable=False),
        sa.Column("edition_identifier", sa.String(255), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(16),
            nullable=False,
            server_default=sa.text("'DRAFT'"),
        ),
        sa.Column("verification_date", sa.Date(), nullable=True),
        sa.Column("legal_status", sa.String(16), nullable=False),
        sa.Column("primary_legal_source_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_edition_id", sa.Uuid(), nullable=True),
        sa.Column("superseded_by_edition_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("fee_schedule_edition_id"),
        _fk("fee_schedule_editions", "primary_legal_source_id", "source_records.source_id"),
        _fk(
            "fee_schedule_editions",
            "supersedes_edition_id",
            "fee_schedule_editions.fee_schedule_edition_id",
        ),
        _fk(
            "fee_schedule_editions",
            "superseded_by_edition_id",
            "fee_schedule_editions.fee_schedule_edition_id",
        ),
        _ck_enum("fee_schedule_editions", "verification_status", ("DRAFT", "VERIFIED")),
        _ck_enum(
            "fee_schedule_editions",
            "legal_status",
            ("CURRENT", "HISTORICAL", "SUPERSEDED", "RETIRED"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name="ck_fse_effective_range",
        ),
        sa.CheckConstraint(
            "(verification_status = 'DRAFT' AND verification_date IS NULL) "
            "OR (verification_status = 'VERIFIED' AND verification_date IS NOT NULL)",
            name="ck_fse_verification_date",
        ),
        sa.CheckConstraint(
            "supersedes_edition_id IS NULL OR supersedes_edition_id != fee_schedule_edition_id",
            name="ck_fse_no_self_supersedes",
        ),
        sa.CheckConstraint(
            "superseded_by_edition_id IS NULL "
            "OR superseded_by_edition_id != fee_schedule_edition_id",
            name="ck_fse_no_self_superseded_by",
        ),
    )
    op.create_index(
        "ix_fee_schedule_editions_effective",
        "fee_schedule_editions",
        ["effective_from", "effective_to"],
    )
    op.create_index(
        "ix_fee_schedule_editions_verification_status",
        "fee_schedule_editions",
        ["verification_status"],
    )
    op.create_index(
        "ix_fee_schedule_editions_primary_legal_source_id",
        "fee_schedule_editions",
        ["primary_legal_source_id"],
    )
    op.create_index(
        "ix_fee_schedule_editions_supersedes_edition_id",
        "fee_schedule_editions",
        ["supersedes_edition_id"],
    )
    op.create_index(
        "ix_fee_schedule_editions_superseded_by_edition_id",
        "fee_schedule_editions",
        ["superseded_by_edition_id"],
    )

    # 5. reference_releases ---------------------------------------------------
    op.create_table(
        "reference_releases",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("fee_schedule_edition_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(32), nullable=False),
        sa.Column("release_sequence", sa.Integer(), nullable=False),
        sa.Column("release_name", sa.String(255), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_bundle_hash", HASH, nullable=True),
        sa.Column("assertion_bundle_hash", HASH, nullable=True),
        sa.Column("rule_bundle_hash", HASH, nullable=True),
        sa.Column("condition_bundle_hash", HASH, nullable=True),
        sa.Column("content_change_summary", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", USER, nullable=False),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("reviewed_by", USER, nullable=True),
        sa.PrimaryKeyConstraint("release_id"),
        _fk(
            "reference_releases",
            "fee_schedule_edition_id",
            "fee_schedule_editions.fee_schedule_edition_id",
        ),
        sa.UniqueConstraint(
            "fee_schedule_edition_id",
            "release_sequence",
            name="uq_reference_releases_edition_sequence",
        ),
        _ck_enum(
            "reference_releases",
            "status",
            ("DRAFT", "SOURCE_VERIFIED", "REVIEWED", "RELEASED", "SUPERSEDED", "RETIRED"),
        ),
        sa.CheckConstraint(
            "status != 'RELEASED' OR released_at IS NOT NULL",
            name="ck_rr_released_at",
        ),
    )
    op.create_index(
        "ix_reference_releases_fee_schedule_edition_id",
        "reference_releases",
        ["fee_schedule_edition_id"],
    )
    op.create_index(
        "ix_reference_releases_edition_status_released",
        "reference_releases",
        ["fee_schedule_edition_id", "status", "released_at"],
    )

    # 6. fee_calculation_rules ------------------------------------------------
    op.create_table(
        "fee_calculation_rules",
        sa.Column("calculation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sa.String(255), nullable=False),
        sa.Column("formula_type", sa.String(32), nullable=False),
        sa.Column("formula_description", sa.Text(), nullable=True),
        sa.Column("rounding_mode", sa.String(32), nullable=False),
        sa.Column("rounding_precision", sa.String(16), nullable=False),
        sa.Column("rounding_stage", sa.String(32), nullable=False),
        sa.Column("rule_hash", HASH, nullable=True),
        sa.Column("rule_hash_algorithm", sa.String(16), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_locator", sa.String(512), nullable=True),
        sa.Column("legal_strength", sa.String(32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("calculation_rule_id"),
        _fk("fee_calculation_rules", "release_id", "reference_releases.release_id"),
        _fk("fee_calculation_rules", "source_id", "source_records.source_id"),
        _ck_enum(
            "fee_calculation_rules",
            "formula_type",
            ("DIRECT_MULTIPLICATION", "PUBLISHED_AMOUNT", "ALTERNATE_METHOD", "FUTURE_STRUCTURE"),
        ),
        _ck_enum(
            "fee_calculation_rules",
            "rounding_mode",
            ("HALF_UP", "HALF_DOWN", "BANKER_ROUNDING", "TRUNCATE", "CEILING", "FLOOR"),
        ),
        _ck_enum(
            "fee_calculation_rules",
            "rounding_precision",
            ("CENT", "EURO", "HALF_CENT", "TENTH_CENT"),
        ),
        _ck_enum(
            "fee_calculation_rules",
            "rounding_stage",
            ("BEFORE_THRESHOLD", "AFTER_THRESHOLD", "AFTER_MAX", "FINAL_RESULT"),
        ),
        _ck_enum("fee_calculation_rules", "rule_hash_algorithm", HASH_ALGORITHMS),
        _ck_enum(
            "fee_calculation_rules",
            "legal_strength",
            ("STATUTORY_EXPLICIT", "OFFICIAL_GUIDANCE", "INTERPRETIVE"),
        ),
        _ck_enum("fee_calculation_rules", "verification_status", VERIFICATION_STATUSES_3),
    )
    op.create_index(
        "ix_fee_calculation_rules_release_id", "fee_calculation_rules", ["release_id"]
    )
    op.create_index("ix_fee_calculation_rules_source_id", "fee_calculation_rules", ["source_id"])

    # 7. factor_rules ---------------------------------------------------------
    op.create_table(
        "factor_rules",
        sa.Column("factor_rule_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sa.String(255), nullable=False),
        sa.Column("threshold_factor", DECIMAL, nullable=False),
        sa.Column("max_factor", DECIMAL, nullable=False),
        sa.Column("scope_type", sa.String(32), nullable=False),
        sa.Column("scope_reference", sa.String(255), nullable=True),
        sa.Column("scope_description", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_locator", sa.String(512), nullable=True),
        sa.Column("legal_strength", sa.String(32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rule_hash", HASH, nullable=True),
        sa.PrimaryKeyConstraint("factor_rule_id"),
        _fk("factor_rules", "release_id", "reference_releases.release_id"),
        _fk("factor_rules", "source_id", "source_records.source_id"),
        _ck_enum(
            "factor_rules",
            "scope_type",
            (
                "STATUTE_SECTION",
                "STATUTORY_GROUP",
                "EXPLICIT_CODE_LIST",
                "INDIVIDUAL_CODE",
                "FUTURE_STRUCTURE",
            ),
        ),
        _ck_enum(
            "factor_rules",
            "legal_strength",
            ("STATUTORY_EXPLICIT", "STATUTORY_DERIVED", "OFFICIAL_GUIDANCE"),
        ),
        _ck_enum("factor_rules", "verification_status", VERIFICATION_STATUSES),
    )
    op.create_index("ix_factor_rules_release_id", "factor_rules", ["release_id"])
    op.create_index("ix_factor_rules_source_id", "factor_rules", ["source_id"])

    # 8. condition_groups -----------------------------------------------------
    op.create_table(
        "condition_groups",
        sa.Column("condition_group_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("logical_operator", sa.String(8), nullable=False),
        sa.Column("parent_group_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.PrimaryKeyConstraint("condition_group_id"),
        _fk("condition_groups", "release_id", "reference_releases.release_id"),
        _fk("condition_groups", "parent_group_id", "condition_groups.condition_group_id"),
        _fk("condition_groups", "source_id", "source_records.source_id"),
        _ck_enum("condition_groups", "logical_operator", ("AND", "OR")),
        _ck_enum("condition_groups", "verification_status", VERIFICATION_STATUSES),
        sa.CheckConstraint(
            "parent_group_id IS NULL OR parent_group_id != condition_group_id",
            name="ck_cg_not_self_parent",
        ),
    )
    op.create_index("ix_condition_groups_release_id", "condition_groups", ["release_id"])
    op.create_index("ix_condition_groups_parent_group_id", "condition_groups", ["parent_group_id"])
    op.create_index("ix_condition_groups_source_id", "condition_groups", ["source_id"])

    # 9. billing_rules --------------------------------------------------------
    op.create_table(
        "billing_rules",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("rule_type", sa.String(32), nullable=False),
        sa.Column("rule_name", sa.String(255), nullable=False),
        sa.Column("rule_description", sa.Text(), nullable=True),
        sa.Column("condition_group_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_locator", sa.String(512), nullable=True),
        sa.Column("temporal_scope", sa.String(32), nullable=False),
        sa.Column("temporal_scope_source_id", sa.Uuid(), nullable=True),
        sa.Column("legal_strength", sa.String(32), nullable=False),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("patient_message_policy_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_hash", HASH, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("rule_id"),
        _fk("billing_rules", "release_id", "reference_releases.release_id"),
        _fk("billing_rules", "condition_group_id", "condition_groups.condition_group_id"),
        _fk("billing_rules", "source_id", "source_records.source_id"),
        _fk("billing_rules", "temporal_scope_source_id", "source_records.source_id"),
        _fk("billing_rules", "patient_message_policy_id", "patient_message_policies.policy_id"),
        sa.UniqueConstraint("condition_group_id", name="uq_billing_rules_condition_group"),
        _ck_enum(
            "billing_rules",
            "rule_type",
            (
                "EXCLUSION",
                "TIME_MINIMUM",
                "FREQUENCY_MAX",
                "JUSTIFICATION_REQUIRED",
                "COMBINATION_PROHIBITED",
                "ORDERING_DEPENDENCY",
                "ANALOG_RESTRICTION",
                "SURCHARGE_RESTRICTION",
                "CONTEXT_REQUIREMENT",
            ),
        ),
        _ck_enum("billing_rules", "temporal_scope", ("SOURCE_DEFINED", "NOT_APPLICABLE", "UNKNOWN")),
        _ck_enum(
            "billing_rules",
            "legal_strength",
            ("STATUTORY_EXPLICIT", "STATUTORY_DERIVED", "OFFICIAL_GUIDANCE", "INTERPRETIVE"),
        ),
        _ck_enum("billing_rules", "verification_status", VERIFICATION_STATUSES_3),
        sa.CheckConstraint(
            "temporal_scope_source_id IS NULL OR temporal_scope = 'SOURCE_DEFINED'",
            name="ck_br_temporal_source",
        ),
    )
    op.create_index("ix_billing_rules_release_id", "billing_rules", ["release_id"])
    op.create_index("ix_billing_rules_source_id", "billing_rules", ["source_id"])
    op.create_index(
        "ix_billing_rules_temporal_scope_source_id", "billing_rules", ["temporal_scope_source_id"]
    )
    op.create_index(
        "ix_billing_rules_patient_message_policy_id",
        "billing_rules",
        ["patient_message_policy_id"],
    )

    # 10. billing_rule_conditions ---------------------------------------------
    op.create_table(
        "billing_rule_conditions",
        sa.Column("condition_id", sa.Uuid(), nullable=False),
        sa.Column("condition_group_id", sa.Uuid(), nullable=False),
        sa.Column("operator", sa.String(64), nullable=False),
        sa.Column("subject", sa.String(128), nullable=False),
        sa.Column("operand", _json(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.PrimaryKeyConstraint("condition_id"),
        _fk(
            "billing_rule_conditions",
            "condition_group_id",
            "condition_groups.condition_group_id",
        ),
        _fk("billing_rule_conditions", "source_id", "source_records.source_id"),
        _ck_enum("billing_rule_conditions", "verification_status", VERIFICATION_STATUSES_2),
    )
    op.create_index(
        "ix_billing_rule_conditions_condition_group_id",
        "billing_rule_conditions",
        ["condition_group_id"],
    )
    op.create_index(
        "ix_billing_rule_conditions_source_id", "billing_rule_conditions", ["source_id"]
    )

    # 11. goa_reference_entries -----------------------------------------------
    op.create_table(
        "goa_reference_entries",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(16), nullable=False),
        sa.Column("official_title", sa.String(512), nullable=False),
        sa.Column("patient_title", sa.String(512), nullable=True),
        sa.Column("section", sa.String(64), nullable=True),
        sa.Column("subsection", sa.String(64), nullable=True),
        sa.Column("category", sa.String(16), nullable=False),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("point_value_eur", DECIMAL, nullable=True),
        sa.Column("simple_fee", DECIMAL, nullable=True),
        sa.Column("threshold_factor", DECIMAL, nullable=True),
        sa.Column("max_factor", DECIMAL, nullable=True),
        sa.Column("threshold_fee", DECIMAL, nullable=True),
        sa.Column("max_fee", DECIMAL, nullable=True),
        sa.Column("factor_rule_id", sa.Uuid(), nullable=False),
        sa.Column("fee_calculation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("duration_rule_id", sa.Uuid(), nullable=True),
        sa.Column("frequency_rule_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("superseded_by_entry_id", sa.Uuid(), nullable=True),
        sa.Column("primary_source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_hash", HASH, nullable=True),
        sa.PrimaryKeyConstraint("entry_id"),
        _fk("goa_reference_entries", "release_id", "reference_releases.release_id"),
        _fk("goa_reference_entries", "factor_rule_id", "factor_rules.factor_rule_id"),
        _fk(
            "goa_reference_entries",
            "fee_calculation_rule_id",
            "fee_calculation_rules.calculation_rule_id",
        ),
        _fk("goa_reference_entries", "duration_rule_id", "billing_rules.rule_id"),
        _fk("goa_reference_entries", "frequency_rule_id", "billing_rules.rule_id"),
        _fk("goa_reference_entries", "superseded_by_entry_id", "goa_reference_entries.entry_id"),
        _fk("goa_reference_entries", "primary_source_id", "source_records.source_id"),
        _ck_enum(
            "goa_reference_entries", "category", ("PERSONAL", "TECHNICAL", "SURCHARGE", "ANALOG")
        ),
        _ck_enum("goa_reference_entries", "verification_status", VERIFICATION_STATUSES),
        sa.CheckConstraint(
            "superseded_by_entry_id IS NULL OR superseded_by_entry_id != entry_id",
            name="ck_gre_not_self_superseded",
        ),
    )
    op.create_index(
        "ix_goa_reference_entries_release_code", "goa_reference_entries", ["release_id", "code"]
    )
    op.create_index(
        "ix_goa_reference_entries_factor_rule_id", "goa_reference_entries", ["factor_rule_id"]
    )
    op.create_index(
        "ix_goa_reference_entries_fee_calculation_rule_id",
        "goa_reference_entries",
        ["fee_calculation_rule_id"],
    )
    op.create_index(
        "ix_goa_reference_entries_duration_rule_id", "goa_reference_entries", ["duration_rule_id"]
    )
    op.create_index(
        "ix_goa_reference_entries_frequency_rule_id",
        "goa_reference_entries",
        ["frequency_rule_id"],
    )
    op.create_index(
        "ix_goa_reference_entries_primary_source_id",
        "goa_reference_entries",
        ["primary_source_id"],
    )
    op.create_index(
        "ix_goa_reference_entries_superseded_by_entry_id",
        "goa_reference_entries",
        ["superseded_by_entry_id"],
    )

    # 12. billing_rule_codes --------------------------------------------------
    op.create_table(
        "billing_rule_codes",
        sa.Column("rule_code_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("rule_code_id"),
        _fk("billing_rule_codes", "rule_id", "billing_rules.rule_id"),
        _fk("billing_rule_codes", "entry_id", "goa_reference_entries.entry_id"),
        _ck_enum(
            "billing_rule_codes", "role", ("PRIMARY", "REQUIRED", "EXCLUDED", "RELATED", "ALTERNATE")
        ),
    )
    op.create_index("ix_billing_rule_codes_rule_id", "billing_rule_codes", ["rule_id"])
    op.create_index("ix_billing_rule_codes_entry_id", "billing_rule_codes", ["entry_id"])

    # 13. reference_assertions ------------------------------------------------
    op.create_table(
        "reference_assertions",
        sa.Column("assertion_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(32), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(128), nullable=False),
        sa.Column("assertion_value", _json(), nullable=False),
        sa.Column("normalized_value", _json(), nullable=True),
        sa.Column("value_type", sa.String(16), nullable=False),
        sa.Column("derivation_type", sa.String(32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("calculation_rule_id", sa.Uuid(), nullable=True),
        sa.Column("source_locator", sa.String(512), nullable=True),
        sa.Column("source_class", sa.String(32), nullable=True),
        sa.Column("legal_strength", sa.String(32), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verification_method", sa.String(64), nullable=True),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assertion_hash", HASH, nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("assertion_id"),
        _fk("reference_assertions", "release_id", "reference_releases.release_id"),
        sa.ForeignKeyConstraint(
            ["source_id", "source_class"],
            ["source_records.source_id", "source_records.source_class"],
            name="fk_reference_assertions_source_id_class",
            ondelete="RESTRICT",
        ),
        _fk(
            "reference_assertions",
            "calculation_rule_id",
            "fee_calculation_rules.calculation_rule_id",
        ),
        _ck_enum(
            "reference_assertions",
            "subject_type",
            ("GOA_ENTRY", "FACTOR_RULE", "FEE_CALCULATION", "BILLING_RULE", "ANALOG_REFERENCE"),
        ),
        _ck_enum(
            "reference_assertions",
            "value_type",
            ("INTEGER", "DECIMAL", "STRING", "DATE", "ENUM", "BOOLEAN"),
        ),
        _ck_enum(
            "reference_assertions",
            "derivation_type",
            ("DIRECT_SOURCE", "CALCULATED", "CURATED_INTERNAL"),
        ),
        _ck_enum("reference_assertions", "source_class", SOURCE_CLASSES),
        _ck_enum(
            "reference_assertions",
            "legal_strength",
            (
                "STATUTORY_EXPLICIT",
                "STATUTORY_DERIVED",
                "OFFICIAL_GUIDANCE",
                "INTERPRETIVE",
                "SOURCE_NOT_FOUND",
            ),
        ),
        _ck_enum("reference_assertions", "verification_status", VERIFICATION_STATUSES),
        _ck_enum(
            "reference_assertions",
            "verification_method",
            ("PRIMARY_SOURCE_MATCH", "MANUAL_REVIEW"),
        ),
        sa.CheckConstraint(
            "(source_id IS NULL AND source_class IS NULL) "
            "OR (source_id IS NOT NULL AND source_class IS NOT NULL)",
            name="ck_ra_source_class_pair",
        ),
        sa.CheckConstraint(
            "(derivation_type = 'DIRECT_SOURCE' AND source_id IS NOT NULL "
            "AND calculation_rule_id IS NULL) "
            "OR (derivation_type = 'CALCULATED' AND source_id IS NULL "
            "AND calculation_rule_id IS NOT NULL) "
            "OR (derivation_type = 'CURATED_INTERNAL' AND source_id IS NOT NULL "
            "AND source_class = 'SOURCE_E_PROOFMED')",
            name="ck_ra_inv016",
        ),
    )
    op.create_index(
        "ix_reference_assertions_release_subject",
        "reference_assertions",
        ["release_id", "subject_type", "subject_id"],
    )
    op.create_index("ix_reference_assertions_source_id", "reference_assertions", ["source_id"])
    op.create_index(
        "ix_reference_assertions_calculation_rule_id",
        "reference_assertions",
        ["calculation_rule_id"],
    )

    # 14. assertion_dependencies ----------------------------------------------
    op.create_table(
        "assertion_dependencies",
        sa.Column("dependency_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("derived_assertion_id", sa.Uuid(), nullable=False),
        sa.Column("input_assertion_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_role", sa.String(32), nullable=False),
        sa.Column("calculation_rule_id", sa.Uuid(), nullable=False),
        sa.Column("ordering", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("dependency_id"),
        _fk("assertion_dependencies", "release_id", "reference_releases.release_id"),
        _fk(
            "assertion_dependencies", "derived_assertion_id", "reference_assertions.assertion_id"
        ),
        _fk("assertion_dependencies", "input_assertion_id", "reference_assertions.assertion_id"),
        _fk(
            "assertion_dependencies",
            "calculation_rule_id",
            "fee_calculation_rules.calculation_rule_id",
        ),
        sa.CheckConstraint(
            "derived_assertion_id != input_assertion_id", name="ck_ad_not_self"
        ),
    )
    op.create_index(
        "ix_assertion_dependencies_release_id", "assertion_dependencies", ["release_id"]
    )
    op.create_index(
        "ix_assertion_dependencies_derived_assertion_id",
        "assertion_dependencies",
        ["derived_assertion_id"],
    )
    op.create_index(
        "ix_assertion_dependencies_input_assertion_id",
        "assertion_dependencies",
        ["input_assertion_id"],
    )
    op.create_index(
        "ix_assertion_dependencies_calculation_rule_id",
        "assertion_dependencies",
        ["calculation_rule_id"],
    )

    # 15. analog_references ---------------------------------------------------
    op.create_table(
        "analog_references",
        sa.Column("analog_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("analog_identifier", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("analog_equivalent_reference_code", sa.String(16), nullable=True),
        sa.Column("analog_equivalent_description", sa.Text(), nullable=True),
        sa.Column("recommendation_type", sa.String(32), nullable=False),
        sa.Column("recommendation_source_id", sa.Uuid(), nullable=True),
        sa.Column("legal_strength", sa.String(32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(32),
            nullable=False,
            server_default=sa.text("'UNVERIFIED'"),
        ),
        sa.Column("verified_by", USER, nullable=True),
        sa.Column("patient_message_policy_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("analog_id"),
        _fk("analog_references", "release_id", "reference_releases.release_id"),
        _fk("analog_references", "recommendation_source_id", "source_records.source_id"),
        _fk(
            "analog_references",
            "patient_message_policy_id",
            "patient_message_policies.policy_id",
        ),
        _ck_enum(
            "analog_references",
            "recommendation_type",
            ("STATUTORY_EQUIVALENT", "BAK_RECOMMENDED", "QUESTIONABLE", "UNRESOLVED"),
        ),
        _ck_enum(
            "analog_references",
            "legal_strength",
            ("STATUTORY_ANALOG_RULE", "BAK_RECOMMENDATION", "LOCAL_PRACTICE", "UNRESOLVED"),
        ),
        _ck_enum("analog_references", "verification_status", VERIFICATION_STATUSES_3),
    )
    op.create_index("ix_analog_references_release_id", "analog_references", ["release_id"])
    op.create_index(
        "ix_analog_references_recommendation_source_id",
        "analog_references",
        ["recommendation_source_id"],
    )
    op.create_index(
        "ix_analog_references_patient_message_policy_id",
        "analog_references",
        ["patient_message_policy_id"],
    )

    # 16. audit_reference_snapshots -------------------------------------------
    op.create_table(
        "audit_reference_snapshots",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("applicable_fee_schedule_edition_id", sa.Uuid(), nullable=False),
        sa.Column("applicable_reference_release_id", sa.Uuid(), nullable=False),
        sa.Column("audit_engine_version", sa.String(64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entries_used_count", sa.Integer(), nullable=True),
        sa.Column("rules_used_count", sa.Integer(), nullable=True),
        sa.Column("assertions_used_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("snapshot_id"),
        _fk(
            "audit_reference_snapshots",
            "applicable_fee_schedule_edition_id",
            "fee_schedule_editions.fee_schedule_edition_id",
        ),
        _fk(
            "audit_reference_snapshots",
            "applicable_reference_release_id",
            "reference_releases.release_id",
        ),
    )
    op.create_index(
        "ix_audit_reference_snapshots_audit_id", "audit_reference_snapshots", ["audit_id"]
    )
    op.create_index(
        "ix_audit_reference_snapshots_applicable_fee_schedule_edition_id",
        "audit_reference_snapshots",
        ["applicable_fee_schedule_edition_id"],
    )
    op.create_index(
        "ix_audit_reference_snapshots_applicable_reference_release_id",
        "audit_reference_snapshots",
        ["applicable_reference_release_id"],
    )

    # 17. audit_evidence_manifests --------------------------------------------
    op.create_table(
        "audit_evidence_manifests",
        sa.Column("manifest_id", sa.Uuid(), nullable=False),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("fee_schedule_edition_id", sa.Uuid(), nullable=False),
        sa.Column("reference_release_id", sa.Uuid(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entries_used", _json(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("assertions_used", _json(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column(
            "fee_calculation_rules_used", _json(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column("conditions_used", _json(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("rules_applied", _json(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("sources_used", _json(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("structured_findings", _json(), nullable=True),
        sa.Column("manifest_hash", HASH, nullable=True),
        sa.Column("manifest_hash_algorithm", sa.String(16), nullable=True),
        sa.PrimaryKeyConstraint("manifest_id"),
        _fk("audit_evidence_manifests", "snapshot_id", "audit_reference_snapshots.snapshot_id"),
        _fk(
            "audit_evidence_manifests",
            "fee_schedule_edition_id",
            "fee_schedule_editions.fee_schedule_edition_id",
        ),
        _fk("audit_evidence_manifests", "reference_release_id", "reference_releases.release_id"),
        _ck_enum("audit_evidence_manifests", "manifest_hash_algorithm", HASH_ALGORITHMS),
        sa.CheckConstraint(
            "finalized_at IS NULL OR manifest_hash IS NOT NULL",
            name="ck_aem_finalized_has_hash",
        ),
    )
    op.create_index(
        "ix_audit_evidence_manifests_audit_id", "audit_evidence_manifests", ["audit_id"]
    )
    op.create_index(
        "ix_audit_evidence_manifests_snapshot_id", "audit_evidence_manifests", ["snapshot_id"]
    )
    op.create_index(
        "ix_audit_evidence_manifests_fee_schedule_edition_id",
        "audit_evidence_manifests",
        ["fee_schedule_edition_id"],
    )
    op.create_index(
        "ix_audit_evidence_manifests_reference_release_id",
        "audit_evidence_manifests",
        ["reference_release_id"],
    )


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------

DROP_ORDER: tuple[str, ...] = (
    "audit_evidence_manifests",
    "audit_reference_snapshots",
    "analog_references",
    "assertion_dependencies",
    "reference_assertions",
    "billing_rule_codes",
    "goa_reference_entries",
    "billing_rule_conditions",
    "billing_rules",
    "condition_groups",
    "factor_rules",
    "fee_calculation_rules",
    "reference_releases",
    "fee_schedule_editions",
    "verification_records",
    "patient_message_policies",
    "source_records",
)


def downgrade() -> None:
    # INV-022: FINALIZED manifests are never deleted. Refuse the downgrade
    # entirely while any finalized manifest exists.
    bind = op.get_bind()
    finalized = bind.execute(
        sa.text(
            "SELECT COUNT(*) FROM audit_evidence_manifests WHERE finalized_at IS NOT NULL"
        )
    ).scalar_one()
    if finalized:
        raise RuntimeError(
            f"Downgrade refused: {finalized} FINALIZED audit evidence manifest(s) exist "
            "(INV-022). Finalized manifests are immutable and must never be dropped."
        )
    for table_name in DROP_ORDER:
        op.drop_table(table_name)
